// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DAX2.DTT.Convertion.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CheckArguments")]
    public partial class CheckArgumentsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CheckArguments.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CheckArguments", @"	All tuning data under “profile” node in XML will not be imported into database except the data of “endpoint_type” node in default settings.
	If need to import those tuning data, add command argument “--import-profile-tuning” to import tuning data of “profile” node and add command argument “--import-endpoint-port” to import tuning data of “endpoint_port”.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check With No Argument")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void CheckWithNoArgument()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check With No Argument", new string[] {
                        "mytag"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.When("I open the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.When("I set the DB file to DAX2.sdf", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.And("I set the XML file to Tuning_File_Profile.xml", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I click on the convert button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("I should see a message box with the title Great News and the message Successfully" +
                    " Converted the XML to Database shows up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.When("I press OK button on the message box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.And("I close the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "name",
                        "graphic_equalizer_enable",
                        "ieq_enable",
                        "ieq_amount",
                        "mi_dialog_enhancer_steering_enable",
                        "mi_dv_leveler_steering_enable",
                        "mi_ieq_steering_enable",
                        "mi_surround_compressor_steering_enable",
                        "virtualizer_headphone_reverb_gain",
                        "intermediate_profile_audio_optimizer_enable",
                        "intermediate_profile_bass_enhancer_enable",
                        "intermediate_profile_bass_extraction_enable",
                        "intermediate_profile_process_optimizer_enable",
                        "intermediate_profile_regulator_enable",
                        "intermediate_profile_regulator_speaker_dist_enable",
                        "intermediate_profile_surround_decoder_enable",
                        "intermediate_profile_volume_modeler_enable",
                        "intermediate_profile_partial_virtual_bass_enable",
                        "ieq_bands",
                        "geq_bands"});
#line 14
 testRunner.Then("I should be able to query below 0 new records in the table Profile_Tuning of the " +
                    "DAX2 DB", ((string)(null)), table1, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Profile",
                        "Endpoint_Port",
                        "volume_leveler_in_target",
                        "volume_leveler_out_target"});
#line 16
 testRunner.And("I should be able to query below 0 new records in the table Profile_EndpointPort o" +
                    "f the DAX2 DB", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Profile",
                        "Endpoint_Type",
                        "calibration_boost",
                        "dialog_enhancer_enable",
                        "dialog_enhancer_amount",
                        "dialog_enhancer_ducking",
                        "surround_boost",
                        "volmax_boost",
                        "volume_leveler_enable",
                        "volume_leveler_amount",
                        "intermediate_profile_partial_virtualizer_enable"});
            table3.AddRow(new string[] {
                        "auto",
                        "headphone",
                        "0",
                        "1",
                        "10",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table3.AddRow(new string[] {
                        "auto",
                        "other",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "144",
                        "1",
                        "7",
                        "0"});
            table3.AddRow(new string[] {
                        "auto",
                        "passthrough",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "1",
                        "7",
                        "0"});
            table3.AddRow(new string[] {
                        "auto",
                        "speaker",
                        "0",
                        "1",
                        "12",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table3.AddRow(new string[] {
                        "game",
                        "headphone",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "1"});
            table3.AddRow(new string[] {
                        "game",
                        "other",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "game",
                        "passthrough",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "0",
                        "1",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "game",
                        "speaker",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "1"});
            table3.AddRow(new string[] {
                        "movie",
                        "headphone",
                        "0",
                        "1",
                        "10",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table3.AddRow(new string[] {
                        "movie",
                        "other",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "144",
                        "1",
                        "7",
                        "0"});
            table3.AddRow(new string[] {
                        "movie",
                        "passthrough",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "1",
                        "7",
                        "0"});
            table3.AddRow(new string[] {
                        "movie",
                        "speaker",
                        "0",
                        "1",
                        "12",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table3.AddRow(new string[] {
                        "music",
                        "headphone",
                        "0",
                        "0",
                        "7",
                        "0",
                        "48",
                        "144",
                        "1",
                        "4",
                        "0"});
            table3.AddRow(new string[] {
                        "music",
                        "other",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "4",
                        "0"});
            table3.AddRow(new string[] {
                        "music",
                        "passthrough",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "0",
                        "1",
                        "4",
                        "0"});
            table3.AddRow(new string[] {
                        "music",
                        "speaker",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "4",
                        "0"});
            table3.AddRow(new string[] {
                        "off",
                        "headphone",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "off",
                        "other",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "off",
                        "passthrough",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "off",
                        "speaker",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "user1",
                        "headphone",
                        "0",
                        "1",
                        "12",
                        "0",
                        "48",
                        "144",
                        "1",
                        "5",
                        "1"});
            table3.AddRow(new string[] {
                        "user1",
                        "other",
                        "0",
                        "1",
                        "12",
                        "0",
                        "0",
                        "144",
                        "1",
                        "5",
                        "0"});
            table3.AddRow(new string[] {
                        "user1",
                        "passthrough",
                        "0",
                        "1",
                        "12",
                        "0",
                        "0",
                        "0",
                        "1",
                        "5",
                        "0"});
            table3.AddRow(new string[] {
                        "user1",
                        "speaker",
                        "0",
                        "1",
                        "14",
                        "0",
                        "48",
                        "144",
                        "1",
                        "5",
                        "1"});
            table3.AddRow(new string[] {
                        "voice",
                        "headphone",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "voice",
                        "other",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "voice",
                        "passthrough",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "voice",
                        "speaker",
                        "0",
                        "1",
                        "16",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
#line 18
 testRunner.And("I should be able to query below 28 new records in the table Profile_EndpointType " +
                    "of the DAX2 DB", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Argument --import-endpoint-port")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void CheckArgument_Import_Endpoint_Port()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Argument --import-endpoint-port", new string[] {
                        "mytag"});
#line 50
this.ScenarioSetup(scenarioInfo);
#line 51
 testRunner.When("I open the DTT conversion tool with argument --import-endpoint-port", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.When("I set the DB file to DAX2.sdf", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.And("I set the XML file to Tuning_File_Profile.xml", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("I click on the convert button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.Then("I should see a message box with the title Great News and the message Successfully" +
                    " Converted the XML to Database shows up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
 testRunner.When("I press OK button on the message box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.And("I close the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "name",
                        "graphic_equalizer_enable",
                        "ieq_enable",
                        "ieq_amount",
                        "mi_dialog_enhancer_steering_enable",
                        "mi_dv_leveler_steering_enable",
                        "mi_ieq_steering_enable",
                        "mi_surround_compressor_steering_enable",
                        "virtualizer_headphone_reverb_gain",
                        "intermediate_profile_audio_optimizer_enable",
                        "intermediate_profile_bass_enhancer_enable",
                        "intermediate_profile_bass_extraction_enable",
                        "intermediate_profile_process_optimizer_enable",
                        "intermediate_profile_regulator_enable",
                        "intermediate_profile_regulator_speaker_dist_enable",
                        "intermediate_profile_surround_decoder_enable",
                        "intermediate_profile_volume_modeler_enable",
                        "intermediate_profile_partial_virtual_bass_enable",
                        "ieq_bands",
                        "geq_bands"});
#line 58
 testRunner.Then("I should be able to query below 0 new records in the table Profile_Tuning of the " +
                    "DAX2 DB", ((string)(null)), table4, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Profile",
                        "Endpoint_Port",
                        "volume_leveler_in_target",
                        "volume_leveler_out_target"});
            table5.AddRow(new string[] {
                        "auto",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "auto",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "auto",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "auto",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "auto",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "auto",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "auto",
                        "usb",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "game",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "game",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "game",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "game",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "game",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "game",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "game",
                        "usb",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "movie",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "movie",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "movie",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "movie",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "movie",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "movie",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "movie",
                        "usb",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "music",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "music",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "music",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "music",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "music",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "music",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "music",
                        "usb",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "off",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "off",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "off",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "off",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "off",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "off",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "off",
                        "usb",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "user1",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "user1",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "user1",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "user1",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "user1",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "user1",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "user1",
                        "usb",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "voice",
                        "bluetooth",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "voice",
                        "hdmi",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "voice",
                        "headphone_port",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "voice",
                        "internal_speaker",
                        "-320",
                        "-320"});
            table5.AddRow(new string[] {
                        "voice",
                        "miracast",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "voice",
                        "other",
                        "-496",
                        "-496"});
            table5.AddRow(new string[] {
                        "voice",
                        "usb",
                        "-320",
                        "-320"});
#line 60
 testRunner.And("I should be able to query below 49 new records in the table Profile_EndpointPort " +
                    "of the DAX2 DB", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Profile",
                        "Endpoint_Type",
                        "calibration_boost",
                        "dialog_enhancer_enable",
                        "dialog_enhancer_amount",
                        "dialog_enhancer_ducking",
                        "surround_boost",
                        "volmax_boost",
                        "volume_leveler_enable",
                        "volume_leveler_amount",
                        "intermediate_profile_partial_virtualizer_enable"});
            table6.AddRow(new string[] {
                        "auto",
                        "headphone",
                        "0",
                        "1",
                        "10",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table6.AddRow(new string[] {
                        "auto",
                        "other",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "144",
                        "1",
                        "7",
                        "0"});
            table6.AddRow(new string[] {
                        "auto",
                        "passthrough",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "1",
                        "7",
                        "0"});
            table6.AddRow(new string[] {
                        "auto",
                        "speaker",
                        "0",
                        "1",
                        "12",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table6.AddRow(new string[] {
                        "game",
                        "headphone",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "1"});
            table6.AddRow(new string[] {
                        "game",
                        "other",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "game",
                        "passthrough",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "0",
                        "1",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "game",
                        "speaker",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "1"});
            table6.AddRow(new string[] {
                        "movie",
                        "headphone",
                        "0",
                        "1",
                        "10",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table6.AddRow(new string[] {
                        "movie",
                        "other",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "144",
                        "1",
                        "7",
                        "0"});
            table6.AddRow(new string[] {
                        "movie",
                        "passthrough",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "1",
                        "7",
                        "0"});
            table6.AddRow(new string[] {
                        "movie",
                        "speaker",
                        "0",
                        "1",
                        "12",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table6.AddRow(new string[] {
                        "music",
                        "headphone",
                        "0",
                        "0",
                        "7",
                        "0",
                        "48",
                        "144",
                        "1",
                        "4",
                        "0"});
            table6.AddRow(new string[] {
                        "music",
                        "other",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "4",
                        "0"});
            table6.AddRow(new string[] {
                        "music",
                        "passthrough",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "0",
                        "1",
                        "4",
                        "0"});
            table6.AddRow(new string[] {
                        "music",
                        "speaker",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "4",
                        "0"});
            table6.AddRow(new string[] {
                        "off",
                        "headphone",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "off",
                        "other",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "off",
                        "passthrough",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "off",
                        "speaker",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "user1",
                        "headphone",
                        "0",
                        "1",
                        "12",
                        "0",
                        "48",
                        "144",
                        "1",
                        "5",
                        "1"});
            table6.AddRow(new string[] {
                        "user1",
                        "other",
                        "0",
                        "1",
                        "12",
                        "0",
                        "0",
                        "144",
                        "1",
                        "5",
                        "0"});
            table6.AddRow(new string[] {
                        "user1",
                        "passthrough",
                        "0",
                        "1",
                        "12",
                        "0",
                        "0",
                        "0",
                        "1",
                        "5",
                        "0"});
            table6.AddRow(new string[] {
                        "user1",
                        "speaker",
                        "0",
                        "1",
                        "14",
                        "0",
                        "48",
                        "144",
                        "1",
                        "5",
                        "1"});
            table6.AddRow(new string[] {
                        "voice",
                        "headphone",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "voice",
                        "other",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "voice",
                        "passthrough",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table6.AddRow(new string[] {
                        "voice",
                        "speaker",
                        "0",
                        "1",
                        "16",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
#line 111
 testRunner.And("I should be able to query below 28 new records in the table Profile_EndpointType " +
                    "of the DAX2 DB", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check Argument --import-profile-tuning")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void CheckArgument_Import_Profile_Tuning()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Argument --import-profile-tuning", new string[] {
                        "mytag"});
#line 143
this.ScenarioSetup(scenarioInfo);
#line 144
 testRunner.When("I open the DTT conversion tool with argument --import-profile-tuning", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 145
 testRunner.When("I set the DB file to DAX2.sdf", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
 testRunner.And("I set the XML file to Tuning_File_Profile.xml", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
 testRunner.And("I click on the convert button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.Then("I should see a message box with the title Great News and the message Successfully" +
                    " Converted the XML to Database shows up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 149
 testRunner.When("I press OK button on the message box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.And("I close the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "name",
                        "graphic_equalizer_enable",
                        "ieq_enable",
                        "ieq_amount",
                        "mi_dialog_enhancer_steering_enable",
                        "mi_dv_leveler_steering_enable",
                        "mi_ieq_steering_enable",
                        "mi_surround_compressor_steering_enable",
                        "virtualizer_headphone_reverb_gain",
                        "intermediate_profile_audio_optimizer_enable",
                        "intermediate_profile_bass_enhancer_enable",
                        "intermediate_profile_bass_extraction_enable",
                        "intermediate_profile_process_optimizer_enable",
                        "intermediate_profile_regulator_enable",
                        "intermediate_profile_regulator_speaker_dist_enable",
                        "intermediate_profile_surround_decoder_enable",
                        "intermediate_profile_volume_modeler_enable",
                        "intermediate_profile_partial_virtual_bass_enable",
                        "ieq_bands",
                        "geq_bands"});
            table7.AddRow(new string[] {
                        "auto",
                        "Dynamic",
                        "0",
                        "1",
                        "10",
                        "1",
                        "1",
                        "1",
                        "1",
                        "0",
                        "1",
                        "1",
                        "0",
                        "0",
                        "1",
                        "1",
                        "1",
                        "0",
                        "1",
                        "ieq_open",
                        "geq_auto_open"});
            table7.AddRow(new string[] {
                        "game",
                        "Game",
                        "0",
                        "0",
                        "10",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1",
                        "0",
                        "0",
                        "1",
                        "1",
                        "1",
                        "0",
                        "1",
                        "ieq_open",
                        "geq_game_off"});
            table7.AddRow(new string[] {
                        "movie",
                        "Movie",
                        "0",
                        "0",
                        "10",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1",
                        "0",
                        "0",
                        "1",
                        "1",
                        "1",
                        "0",
                        "1",
                        "ieq_open",
                        "geq_movie_off"});
            table7.AddRow(new string[] {
                        "music",
                        "Music",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1",
                        "0",
                        "0",
                        "1",
                        "1",
                        "1",
                        "0",
                        "1",
                        "ieq_open",
                        "geq_music_open"});
            table7.AddRow(new string[] {
                        "off",
                        "Off",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "ieq_open",
                        "geq_off_off"});
            table7.AddRow(new string[] {
                        "user1",
                        "Personalized",
                        "1",
                        "0",
                        "10",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1",
                        "0",
                        "0",
                        "1",
                        "1",
                        "1",
                        "0",
                        "1",
                        "ieq_open",
                        "geq_user1_off"});
            table7.AddRow(new string[] {
                        "voice",
                        "Voice",
                        "0",
                        "0",
                        "10",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "1",
                        "0",
                        "0",
                        "0",
                        "1",
                        "1",
                        "1",
                        "0",
                        "0",
                        "ieq_rich",
                        "geq_voice_off"});
#line 151
 testRunner.Then("I should be able to query below 7 new records in the table Profile_Tuning of the " +
                    "DAX2 DB", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Profile",
                        "Endpoint_Port",
                        "volume_leveler_in_target",
                        "volume_leveler_out_target"});
#line 160
 testRunner.And("I should be able to query below 0 new records in the table Profile_EndpointPort o" +
                    "f the DAX2 DB", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Profile",
                        "Endpoint_Type",
                        "calibration_boost",
                        "dialog_enhancer_enable",
                        "dialog_enhancer_amount",
                        "dialog_enhancer_ducking",
                        "surround_boost",
                        "volmax_boost",
                        "volume_leveler_enable",
                        "volume_leveler_amount",
                        "intermediate_profile_partial_virtualizer_enable"});
            table9.AddRow(new string[] {
                        "auto",
                        "headphone",
                        "0",
                        "1",
                        "10",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table9.AddRow(new string[] {
                        "auto",
                        "other",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "144",
                        "1",
                        "7",
                        "0"});
            table9.AddRow(new string[] {
                        "auto",
                        "passthrough",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "1",
                        "7",
                        "0"});
            table9.AddRow(new string[] {
                        "auto",
                        "speaker",
                        "0",
                        "1",
                        "12",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table9.AddRow(new string[] {
                        "game",
                        "headphone",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "1"});
            table9.AddRow(new string[] {
                        "game",
                        "other",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "game",
                        "passthrough",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "0",
                        "1",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "game",
                        "speaker",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "0",
                        "1"});
            table9.AddRow(new string[] {
                        "movie",
                        "headphone",
                        "0",
                        "1",
                        "10",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table9.AddRow(new string[] {
                        "movie",
                        "other",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "144",
                        "1",
                        "7",
                        "0"});
            table9.AddRow(new string[] {
                        "movie",
                        "passthrough",
                        "0",
                        "1",
                        "10",
                        "0",
                        "0",
                        "0",
                        "1",
                        "7",
                        "0"});
            table9.AddRow(new string[] {
                        "movie",
                        "speaker",
                        "0",
                        "1",
                        "12",
                        "0",
                        "96",
                        "144",
                        "1",
                        "7",
                        "1"});
            table9.AddRow(new string[] {
                        "music",
                        "headphone",
                        "0",
                        "0",
                        "7",
                        "0",
                        "48",
                        "144",
                        "1",
                        "4",
                        "0"});
            table9.AddRow(new string[] {
                        "music",
                        "other",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "4",
                        "0"});
            table9.AddRow(new string[] {
                        "music",
                        "passthrough",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "0",
                        "1",
                        "4",
                        "0"});
            table9.AddRow(new string[] {
                        "music",
                        "speaker",
                        "0",
                        "0",
                        "7",
                        "0",
                        "0",
                        "144",
                        "1",
                        "4",
                        "0"});
            table9.AddRow(new string[] {
                        "off",
                        "headphone",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "off",
                        "other",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "off",
                        "passthrough",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "off",
                        "speaker",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "user1",
                        "headphone",
                        "0",
                        "1",
                        "12",
                        "0",
                        "48",
                        "144",
                        "1",
                        "5",
                        "1"});
            table9.AddRow(new string[] {
                        "user1",
                        "other",
                        "0",
                        "1",
                        "12",
                        "0",
                        "0",
                        "144",
                        "1",
                        "5",
                        "0"});
            table9.AddRow(new string[] {
                        "user1",
                        "passthrough",
                        "0",
                        "1",
                        "12",
                        "0",
                        "0",
                        "0",
                        "1",
                        "5",
                        "0"});
            table9.AddRow(new string[] {
                        "user1",
                        "speaker",
                        "0",
                        "1",
                        "14",
                        "0",
                        "48",
                        "144",
                        "1",
                        "5",
                        "1"});
            table9.AddRow(new string[] {
                        "voice",
                        "headphone",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "voice",
                        "other",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "voice",
                        "passthrough",
                        "0",
                        "1",
                        "14",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0",
                        "0"});
            table9.AddRow(new string[] {
                        "voice",
                        "speaker",
                        "0",
                        "1",
                        "16",
                        "0",
                        "0",
                        "144",
                        "0",
                        "0",
                        "0"});
#line 162
 testRunner.And("I should be able to query below 28 new records in the table Profile_EndpointType " +
                    "of the DAX2 DB", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
