// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DAX2.DTT.Convertion.Test.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("IEQ & GEQ data converstion")]
    public partial class IEQGEQDataConverstionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "IEQDataConversion.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "IEQ & GEQ data converstion", "\tAs a profession tuner for Windows platform\r\n\tI want to be able to convert GEQ & " +
                    "IEQ data from the tuning xml to DAX2 DB\r\n\tSo the GEQ and IEQ data can be applied" +
                    " by the DAX2 Windows product", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I have opened the DTT conversion tool with argument --import-profile-tuning", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Convert GEQ and IEQ data")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void ConvertGEQAndIEQData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Convert GEQ and IEQ data", new string[] {
                        "mytag"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 11
 testRunner.When("I set the DB file to DAX2.sdf", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("I set the XML file to Tuning_File_IEQ_GEQ.xml", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I click on the convert button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("I should see a message box with the title Great News and the message Successfully" +
                    " Converted the XML to Database shows up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
 testRunner.When("I press OK button on the message box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.And("I close the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "frequency",
                        "gain"});
            table1.AddRow(new string[] {
                        "geq_auto_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_auto_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_auto_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_auto_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_game_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_game_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_game_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_game_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_movie_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_movie_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_movie_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_movie_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_music_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_music_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_music_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_music_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_off_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_off_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_off_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_off_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_user1_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_user1_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_user1_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_user1_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_voice_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_voice_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_voice_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table1.AddRow(new string[] {
                        "geq_voice_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
#line 17
 testRunner.Then("I should be able to query below 28 new records in the table GEQ_Bands of the DAX2" +
                    " DB", ((string)(null)), table1, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "frequency",
                        "target"});
            table2.AddRow(new string[] {
                        "ieq_focused",
                        "65,136,223,332,467,634,841,1098,1416,1812,2302,2909,3663,4598,5756,7194,8976,1118" +
                            "6,13927,17326",
                        "-419,-112,75,116,113,160,165,80,61,79,98,121,64,70,44,-71,-33,-100,-238,-411"});
            table2.AddRow(new string[] {
                        "ieq_open",
                        "65,136,223,332,467,634,841,1098,1416,1812,2302,2909,3663,4598,5756,7194,8976,1118" +
                            "6,13927,17326",
                        "117,133,188,176,141,149,175,185,185,200,236,242,228,213,182,132,110,68,-27,-240"});
            table2.AddRow(new string[] {
                        "ieq_rich",
                        "65,136,223,332,467,634,841,1098,1416,1812,2302,2909,3663,4598,5756,7194,8976,1118" +
                            "6,13927,17326",
                        "67,95,172,163,168,201,189,242,196,221,192,186,168,139,102,57,35,9,-55,-235"});
#line 47
 testRunner.Then("I should be able to query below 3 new records in the table IEQ_Bands of the DAX2 " +
                    "DB", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update GEQ and IEQ data")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void UpdateGEQAndIEQData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update GEQ and IEQ data", new string[] {
                        "mytag"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 55
 testRunner.And("I convert the tuning file Tuning_File_IEQ_GEQ.xml to the database DAX2.sdf", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I close the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.When("I open the DTT conversion tool with argument --import-profile-tuning", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
 testRunner.And("I set the DB file to DAX2.sdf", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I set the XML file to Tuning_File_IEQ_GEQ_Update.xml", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.When("I click on the convert button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.Then("I should see a message box with the title Already Exists and the message Entries " +
                    "with same System ID exists in the DB.. Would you like to Replace? shows up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 62
 testRunner.When("I press Yes button on the message box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("I should see a message box with the title Great News and the message Successfully" +
                    " Converted the XML to Database shows up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
 testRunner.When("I press OK button on the message box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.And("I close the DTT conversion tool", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "frequency",
                        "gain"});
            table3.AddRow(new string[] {
                        "geq_auto_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9"});
            table3.AddRow(new string[] {
                        "geq_auto_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_auto_open",
                        "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_auto_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_game_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_game_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_game_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_game_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_movie_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_movie_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_movie_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_movie_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_music_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_music_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_music_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_music_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_off_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_off_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_off_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_off_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_user1_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_user1_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_user1_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_user1_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_voice_focused",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_voice_off",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_voice_open",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
            table3.AddRow(new string[] {
                        "geq_voice_rich",
                        "47,141,234,328,469,656,844,1031,1313,1688,2250,3000,3750,4688,5813,7125,9000,1125" +
                            "0,13875,19688",
                        "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"});
#line 66
 testRunner.Then("I should be able to query below 28 new records in the table GEQ_Bands of the DAX2" +
                    " DB", ((string)(null)), table3, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "frequency",
                        "target"});
            table4.AddRow(new string[] {
                        "ieq_focused",
                        "100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119",
                        "-419,-112,75,116,113,160,165,80,61,79,98,121,64,70,44,-71,-33,-100,-238,-411"});
            table4.AddRow(new string[] {
                        "ieq_open",
                        "65,136,223,332,467,634,841,1098,1416,1812,2302,2909,3663,4598,5756,7194,8976,1118" +
                            "6,13927,17326",
                        "50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69"});
            table4.AddRow(new string[] {
                        "ieq_rich",
                        "65,136,223,332,467,634,841,1098,1416,1812,2302,2909,3663,4598,5756,7194,8976,1118" +
                            "6,13927,17326",
                        "67,95,172,163,168,201,189,242,196,221,192,186,168,139,102,57,35,9,-55,-235"});
#line 96
 testRunner.Then("I should be able to query below 3 new records in the table IEQ_Bands of the DAX2 " +
                    "DB", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
